//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMSService.NMSSernice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", ConfigurationName="NMSSernice.TimeSheetBotService_Port")]
    public interface TimeSheetBotService_Port {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeByPhoneNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.GetEmployeeByPhoneNo_Result GetEmployeeByPhoneNo(NMSService.NMSSernice.GetEmployeeByPhoneNo request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeByPhoneNo", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeByPhoneNo_Result> GetEmployeeByPhoneNoAsync(NMSService.NMSSernice.GetEmployeeByPhoneNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:TimeSheetsPerDay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.TimeSheetsPerDay_Result TimeSheetsPerDay(NMSService.NMSSernice.TimeSheetsPerDay request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:TimeSheetsPerDay", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.TimeSheetsPerDay_Result> TimeSheetsPerDayAsync(NMSService.NMSSernice.TimeSheetsPerDay request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:TimeSheetsPerWeek", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.TimeSheetsPerWeek_Result TimeSheetsPerWeek(NMSService.NMSSernice.TimeSheetsPerWeek request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:TimeSheetsPerWeek", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.TimeSheetsPerWeek_Result> TimeSheetsPerWeekAsync(NMSService.NMSSernice.TimeSheetsPerWeek request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.GetEmployeeByID_Result GetEmployeeByID(NMSService.NMSSernice.GetEmployeeByID request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeByID", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeByID_Result> GetEmployeeByIDAsync(NMSService.NMSSernice.GetEmployeeByID request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:AddEmployeeByEMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.AddEmployeeByEMail_Result AddEmployeeByEMail(NMSService.NMSSernice.AddEmployeeByEMail request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:AddEmployeeByEMail", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.AddEmployeeByEMail_Result> AddEmployeeByEMailAsync(NMSService.NMSSernice.AddEmployeeByEMail request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:ValidatePassCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.ValidatePassCode_Result ValidatePassCode(NMSService.NMSSernice.ValidatePassCode request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:ValidatePassCode", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.ValidatePassCode_Result> ValidatePassCodeAsync(NMSService.NMSSernice.ValidatePassCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.GetEmployeeProjects_Result GetEmployeeProjects(NMSService.NMSSernice.GetEmployeeProjects request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeProjects_Result> GetEmployeeProjectsAsync(NMSService.NMSSernice.GetEmployeeProjects request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeTasks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.GetEmployeeTasks_Result GetEmployeeTasks(NMSService.NMSSernice.GetEmployeeTasks request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:GetEmployeeTasks", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeTasks_Result> GetEmployeeTasksAsync(NMSService.NMSSernice.GetEmployeeTasks request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:AddTimeSheet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NMSService.NMSSernice.AddTimeSheet_Result AddTimeSheet(NMSService.NMSSernice.AddTimeSheet request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService:AddTimeSheet", ReplyAction="*")]
        System.Threading.Tasks.Task<NMSService.NMSSernice.AddTimeSheet_Result> AddTimeSheetAsync(NMSService.NMSSernice.AddTimeSheet request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50070")]
    public partial class root : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Employee[] employeeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employee", Order=0)]
        public Employee[] Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50070")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string noField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string phoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("No.", Order=0)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PhoneNo.", Order=3)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Projects", Namespace="urn:microsoft-dynamics-nav/xmlports/x50075")]
    public partial class Projects1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string taskNoField;
        
        private string taskDescriptionField;
        
        private string assignmentCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TaskNo {
            get {
                return this.taskNoField;
            }
            set {
                this.taskNoField = value;
                this.RaisePropertyChanged("TaskNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaskDescription {
            get {
                return this.taskDescriptionField;
            }
            set {
                this.taskDescriptionField = value;
                this.RaisePropertyChanged("TaskDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AssignmentCode {
            get {
                return this.assignmentCodeField;
            }
            set {
                this.assignmentCodeField = value;
                this.RaisePropertyChanged("AssignmentCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="root", Namespace="urn:microsoft-dynamics-nav/xmlports/x50075")]
    public partial class root5 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Projects1[] projectsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Projects", Order=0)]
        public Projects1[] Projects {
            get {
                return this.projectsField;
            }
            set {
                this.projectsField = value;
                this.RaisePropertyChanged("Projects");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50074")]
    public partial class Projects : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string projectNoField;
        
        private string projectDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProjectNo {
            get {
                return this.projectNoField;
            }
            set {
                this.projectNoField = value;
                this.RaisePropertyChanged("ProjectNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ProjectDescription {
            get {
                return this.projectDescriptionField;
            }
            set {
                this.projectDescriptionField = value;
                this.RaisePropertyChanged("ProjectDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="root", Namespace="urn:microsoft-dynamics-nav/xmlports/x50074")]
    public partial class root4 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Projects[] projectsField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Projects", Order=0)]
        public Projects[] Projects {
            get {
                return this.projectsField;
            }
            set {
                this.projectsField = value;
                this.RaisePropertyChanged("Projects");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Employee", Namespace="urn:microsoft-dynamics-nav/xmlports/x50073")]
    public partial class Employee1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string noField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("No.", Order=0)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="root", Namespace="urn:microsoft-dynamics-nav/xmlports/x50073")]
    public partial class root3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Employee1[] employeeField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Employee", Order=0)]
        public Employee1[] Employee {
            get {
                return this.employeeField;
            }
            set {
                this.employeeField = value;
                this.RaisePropertyChanged("Employee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TimeSheet", Namespace="urn:microsoft-dynamics-nav/xmlports/x50072")]
    public partial class TimeSheet1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] postingDateField;
        
        private string[] dayNameField;
        
        private string[] quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PostingDate", Order=0)]
        public string[] PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
                this.RaisePropertyChanged("PostingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DayName", Order=1)]
        public string[] DayName {
            get {
                return this.dayNameField;
            }
            set {
                this.dayNameField = value;
                this.RaisePropertyChanged("DayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Quantity", Order=2)]
        public string[] Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="root", Namespace="urn:microsoft-dynamics-nav/xmlports/x50072")]
    public partial class root2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeSheet1[] timeSheetField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeSheet", Order=0)]
        public TimeSheet1[] TimeSheet {
            get {
                return this.timeSheetField;
            }
            set {
                this.timeSheetField = value;
                this.RaisePropertyChanged("TimeSheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-nav/xmlports/x50071")]
    public partial class TimeSheet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string postingDateField;
        
        private string dayNameField;
        
        private string projectNoField;
        
        private string assignementCodeField;
        
        private string quantityField;
        
        private string commentField;
        
        private string jobTaskFullNoField;
        
        private string taskDescriptionField;
        
        private string externalNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PostingDate {
            get {
                return this.postingDateField;
            }
            set {
                this.postingDateField = value;
                this.RaisePropertyChanged("PostingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DayName {
            get {
                return this.dayNameField;
            }
            set {
                this.dayNameField = value;
                this.RaisePropertyChanged("DayName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProjectNo.", Order=2)]
        public string ProjectNo {
            get {
                return this.projectNoField;
            }
            set {
                this.projectNoField = value;
                this.RaisePropertyChanged("ProjectNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AssignementCode {
            get {
                return this.assignementCodeField;
            }
            set {
                this.assignementCodeField = value;
                this.RaisePropertyChanged("AssignementCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
                this.RaisePropertyChanged("Comment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("JobTaskFullNo.", Order=6)]
        public string JobTaskFullNo {
            get {
                return this.jobTaskFullNoField;
            }
            set {
                this.jobTaskFullNoField = value;
                this.RaisePropertyChanged("JobTaskFullNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TaskDescription {
            get {
                return this.taskDescriptionField;
            }
            set {
                this.taskDescriptionField = value;
                this.RaisePropertyChanged("TaskDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExternalNo.", Order=8)]
        public string ExternalNo {
            get {
                return this.externalNoField;
            }
            set {
                this.externalNoField = value;
                this.RaisePropertyChanged("ExternalNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="root", Namespace="urn:microsoft-dynamics-nav/xmlports/x50071")]
    public partial class root1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TimeSheet[] timeSheetField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TimeSheet", Order=0)]
        public TimeSheet[] TimeSheet {
            get {
                return this.timeSheetField;
            }
            set {
                this.timeSheetField = value;
                this.RaisePropertyChanged("TimeSheet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeByPhoneNo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeByPhoneNo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public string phoneNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root employeeXMLPort;
        
        public GetEmployeeByPhoneNo() {
        }
        
        public GetEmployeeByPhoneNo(string phoneNo, NMSService.NMSSernice.root employeeXMLPort) {
            this.phoneNo = phoneNo;
            this.employeeXMLPort = employeeXMLPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeByPhoneNo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeByPhoneNo_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public NMSService.NMSSernice.root employeeXMLPort;
        
        public GetEmployeeByPhoneNo_Result() {
        }
        
        public GetEmployeeByPhoneNo_Result(NMSService.NMSSernice.root employeeXMLPort) {
            this.employeeXMLPort = employeeXMLPort;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeSheetsPerDay", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class TimeSheetsPerDay {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dateP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string employeeNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public NMSService.NMSSernice.root1 timeSheetPerDayXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string errorText;
        
        public TimeSheetsPerDay() {
        }
        
        public TimeSheetsPerDay(System.DateTime dateP, string employeeNoP, NMSService.NMSSernice.root1 timeSheetPerDayXMLPort, string errorText) {
            this.dateP = dateP;
            this.employeeNoP = employeeNoP;
            this.timeSheetPerDayXMLPort = timeSheetPerDayXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeSheetsPerDay_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class TimeSheetsPerDay_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root1 timeSheetPerDayXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public TimeSheetsPerDay_Result() {
        }
        
        public TimeSheetsPerDay_Result(int return_value, NMSService.NMSSernice.root1 timeSheetPerDayXMLPort, string errorText) {
            this.return_value = return_value;
            this.timeSheetPerDayXMLPort = timeSheetPerDayXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeSheetsPerWeek", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class TimeSheetsPerWeek {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDateP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endDateP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string employeeNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public NMSService.NMSSernice.root2 timeSheetPerWeekXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=4)]
        public string errorText;
        
        public TimeSheetsPerWeek() {
        }
        
        public TimeSheetsPerWeek(System.DateTime startDateP, System.DateTime endDateP, string employeeNoP, NMSService.NMSSernice.root2 timeSheetPerWeekXMLPort, string errorText) {
            this.startDateP = startDateP;
            this.endDateP = endDateP;
            this.employeeNoP = employeeNoP;
            this.timeSheetPerWeekXMLPort = timeSheetPerWeekXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TimeSheetsPerWeek_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class TimeSheetsPerWeek_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root2 timeSheetPerWeekXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public TimeSheetsPerWeek_Result() {
        }
        
        public TimeSheetsPerWeek_Result(int return_value, NMSService.NMSSernice.root2 timeSheetPerWeekXMLPort, string errorText) {
            this.return_value = return_value;
            this.timeSheetPerWeekXMLPort = timeSheetPerWeekXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeByID", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeByID {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int channelType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string channelID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public NMSService.NMSSernice.root3 employeeByIDXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string errorText;
        
        public GetEmployeeByID() {
        }
        
        public GetEmployeeByID(int channelType, string channelID, NMSService.NMSSernice.root3 employeeByIDXMLPort, string errorText) {
            this.channelType = channelType;
            this.channelID = channelID;
            this.employeeByIDXMLPort = employeeByIDXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeByID_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeByID_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root3 employeeByIDXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public GetEmployeeByID_Result() {
        }
        
        public GetEmployeeByID_Result(int return_value, NMSService.NMSSernice.root3 employeeByIDXMLPort, string errorText) {
            this.return_value = return_value;
            this.employeeByIDXMLPort = employeeByIDXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmployeeByEMail", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class AddEmployeeByEMail {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int channelType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string eMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=4)]
        public string errorText;
        
        public AddEmployeeByEMail() {
        }
        
        public AddEmployeeByEMail(int channelType, string eMail, string firstName, string lastName, string errorText) {
            this.channelType = channelType;
            this.eMail = eMail;
            this.firstName = firstName;
            this.lastName = lastName;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddEmployeeByEMail_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class AddEmployeeByEMail_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string errorText;
        
        public AddEmployeeByEMail_Result() {
        }
        
        public AddEmployeeByEMail_Result(int return_value, string firstName, string lastName, string errorText) {
            this.return_value = return_value;
            this.firstName = firstName;
            this.lastName = lastName;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePassCode", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class ValidatePassCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int channelType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string eMail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string passCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string channelID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=4)]
        public NMSService.NMSSernice.root3 employeeByIDXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=5)]
        public string errorText;
        
        public ValidatePassCode() {
        }
        
        public ValidatePassCode(int channelType, string eMail, string passCode, string channelID, NMSService.NMSSernice.root3 employeeByIDXMLPort, string errorText) {
            this.channelType = channelType;
            this.eMail = eMail;
            this.passCode = passCode;
            this.channelID = channelID;
            this.employeeByIDXMLPort = employeeByIDXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidatePassCode_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class ValidatePassCode_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root3 employeeByIDXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public ValidatePassCode_Result() {
        }
        
        public ValidatePassCode_Result(int return_value, NMSService.NMSSernice.root3 employeeByIDXMLPort, string errorText) {
            this.return_value = return_value;
            this.employeeByIDXMLPort = employeeByIDXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeProjects", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeProjects {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public string employeeNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root4 employeeProjectsXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public GetEmployeeProjects() {
        }
        
        public GetEmployeeProjects(string employeeNoP, NMSService.NMSSernice.root4 employeeProjectsXMLPort, string errorText) {
            this.employeeNoP = employeeNoP;
            this.employeeProjectsXMLPort = employeeProjectsXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeProjects_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeProjects_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root4 employeeProjectsXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public GetEmployeeProjects_Result() {
        }
        
        public GetEmployeeProjects_Result(int return_value, NMSService.NMSSernice.root4 employeeProjectsXMLPort, string errorText) {
            this.return_value = return_value;
            this.employeeProjectsXMLPort = employeeProjectsXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeTasks", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeTasks {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public string employeeNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string projectNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public NMSService.NMSSernice.root5 employeeTasksXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string errorText;
        
        public GetEmployeeTasks() {
        }
        
        public GetEmployeeTasks(string employeeNoP, string projectNoP, NMSService.NMSSernice.root5 employeeTasksXMLPort, string errorText) {
            this.employeeNoP = employeeNoP;
            this.projectNoP = projectNoP;
            this.employeeTasksXMLPort = employeeTasksXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeTasks_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class GetEmployeeTasks_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public NMSService.NMSSernice.root5 employeeTasksXMLPort;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string errorText;
        
        public GetEmployeeTasks_Result() {
        }
        
        public GetEmployeeTasks_Result(int return_value, NMSService.NMSSernice.root5 employeeTasksXMLPort, string errorText) {
            this.return_value = return_value;
            this.employeeTasksXMLPort = employeeTasksXMLPort;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTimeSheet", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class AddTimeSheet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public string employeeNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dateP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=2)]
        public string projectNoP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=3)]
        public string assignmentCodeP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=4)]
        public decimal qtyP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=5)]
        public string commentP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=6)]
        public string errorText;
        
        public AddTimeSheet() {
        }
        
        public AddTimeSheet(string employeeNoP, System.DateTime dateP, string projectNoP, string assignmentCodeP, decimal qtyP, string commentP, string errorText) {
            this.employeeNoP = employeeNoP;
            this.dateP = dateP;
            this.projectNoP = projectNoP;
            this.assignmentCodeP = assignmentCodeP;
            this.qtyP = qtyP;
            this.commentP = commentP;
            this.errorText = errorText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddTimeSheet_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", IsWrapped=true)]
    public partial class AddTimeSheet_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=0)]
        public int return_value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TimeSheetBotService", Order=1)]
        public string errorText;
        
        public AddTimeSheet_Result() {
        }
        
        public AddTimeSheet_Result(int return_value, string errorText) {
            this.return_value = return_value;
            this.errorText = errorText;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TimeSheetBotService_PortChannel : NMSService.NMSSernice.TimeSheetBotService_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeSheetBotService_PortClient : System.ServiceModel.ClientBase<NMSService.NMSSernice.TimeSheetBotService_Port>, NMSService.NMSSernice.TimeSheetBotService_Port {
        
        public TimeSheetBotService_PortClient() {
        }
        
        public TimeSheetBotService_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeSheetBotService_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetBotService_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeSheetBotService_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.GetEmployeeByPhoneNo_Result NMSService.NMSSernice.TimeSheetBotService_Port.GetEmployeeByPhoneNo(NMSService.NMSSernice.GetEmployeeByPhoneNo request) {
            return base.Channel.GetEmployeeByPhoneNo(request);
        }
        
        public void GetEmployeeByPhoneNo(string phoneNo, ref NMSService.NMSSernice.root employeeXMLPort) {
            NMSService.NMSSernice.GetEmployeeByPhoneNo inValue = new NMSService.NMSSernice.GetEmployeeByPhoneNo();
            inValue.phoneNo = phoneNo;
            inValue.employeeXMLPort = employeeXMLPort;
            NMSService.NMSSernice.GetEmployeeByPhoneNo_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).GetEmployeeByPhoneNo(inValue);
            employeeXMLPort = retVal.employeeXMLPort;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeByPhoneNo_Result> GetEmployeeByPhoneNoAsync(NMSService.NMSSernice.GetEmployeeByPhoneNo request) {
            return base.Channel.GetEmployeeByPhoneNoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.TimeSheetsPerDay_Result NMSService.NMSSernice.TimeSheetBotService_Port.TimeSheetsPerDay(NMSService.NMSSernice.TimeSheetsPerDay request) {
            return base.Channel.TimeSheetsPerDay(request);
        }
        
        public int TimeSheetsPerDay(System.DateTime dateP, string employeeNoP, ref NMSService.NMSSernice.root1 timeSheetPerDayXMLPort, ref string errorText) {
            NMSService.NMSSernice.TimeSheetsPerDay inValue = new NMSService.NMSSernice.TimeSheetsPerDay();
            inValue.dateP = dateP;
            inValue.employeeNoP = employeeNoP;
            inValue.timeSheetPerDayXMLPort = timeSheetPerDayXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.TimeSheetsPerDay_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).TimeSheetsPerDay(inValue);
            timeSheetPerDayXMLPort = retVal.timeSheetPerDayXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.TimeSheetsPerDay_Result> TimeSheetsPerDayAsync(NMSService.NMSSernice.TimeSheetsPerDay request) {
            return base.Channel.TimeSheetsPerDayAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.TimeSheetsPerWeek_Result NMSService.NMSSernice.TimeSheetBotService_Port.TimeSheetsPerWeek(NMSService.NMSSernice.TimeSheetsPerWeek request) {
            return base.Channel.TimeSheetsPerWeek(request);
        }
        
        public int TimeSheetsPerWeek(System.DateTime startDateP, System.DateTime endDateP, string employeeNoP, ref NMSService.NMSSernice.root2 timeSheetPerWeekXMLPort, ref string errorText) {
            NMSService.NMSSernice.TimeSheetsPerWeek inValue = new NMSService.NMSSernice.TimeSheetsPerWeek();
            inValue.startDateP = startDateP;
            inValue.endDateP = endDateP;
            inValue.employeeNoP = employeeNoP;
            inValue.timeSheetPerWeekXMLPort = timeSheetPerWeekXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.TimeSheetsPerWeek_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).TimeSheetsPerWeek(inValue);
            timeSheetPerWeekXMLPort = retVal.timeSheetPerWeekXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.TimeSheetsPerWeek_Result> TimeSheetsPerWeekAsync(NMSService.NMSSernice.TimeSheetsPerWeek request) {
            return base.Channel.TimeSheetsPerWeekAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.GetEmployeeByID_Result NMSService.NMSSernice.TimeSheetBotService_Port.GetEmployeeByID(NMSService.NMSSernice.GetEmployeeByID request) {
            return base.Channel.GetEmployeeByID(request);
        }
        
        public int GetEmployeeByID(int channelType, string channelID, ref NMSService.NMSSernice.root3 employeeByIDXMLPort, ref string errorText) {
            NMSService.NMSSernice.GetEmployeeByID inValue = new NMSService.NMSSernice.GetEmployeeByID();
            inValue.channelType = channelType;
            inValue.channelID = channelID;
            inValue.employeeByIDXMLPort = employeeByIDXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.GetEmployeeByID_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).GetEmployeeByID(inValue);
            employeeByIDXMLPort = retVal.employeeByIDXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeByID_Result> GetEmployeeByIDAsync(NMSService.NMSSernice.GetEmployeeByID request) {
            return base.Channel.GetEmployeeByIDAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.AddEmployeeByEMail_Result NMSService.NMSSernice.TimeSheetBotService_Port.AddEmployeeByEMail(NMSService.NMSSernice.AddEmployeeByEMail request) {
            return base.Channel.AddEmployeeByEMail(request);
        }
        
        public int AddEmployeeByEMail(int channelType, string eMail, ref string firstName, ref string lastName, ref string errorText) {
            NMSService.NMSSernice.AddEmployeeByEMail inValue = new NMSService.NMSSernice.AddEmployeeByEMail();
            inValue.channelType = channelType;
            inValue.eMail = eMail;
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.errorText = errorText;
            NMSService.NMSSernice.AddEmployeeByEMail_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).AddEmployeeByEMail(inValue);
            firstName = retVal.firstName;
            lastName = retVal.lastName;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.AddEmployeeByEMail_Result> AddEmployeeByEMailAsync(NMSService.NMSSernice.AddEmployeeByEMail request) {
            return base.Channel.AddEmployeeByEMailAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.ValidatePassCode_Result NMSService.NMSSernice.TimeSheetBotService_Port.ValidatePassCode(NMSService.NMSSernice.ValidatePassCode request) {
            return base.Channel.ValidatePassCode(request);
        }
        
        public int ValidatePassCode(int channelType, string eMail, string passCode, string channelID, ref NMSService.NMSSernice.root3 employeeByIDXMLPort, ref string errorText) {
            NMSService.NMSSernice.ValidatePassCode inValue = new NMSService.NMSSernice.ValidatePassCode();
            inValue.channelType = channelType;
            inValue.eMail = eMail;
            inValue.passCode = passCode;
            inValue.channelID = channelID;
            inValue.employeeByIDXMLPort = employeeByIDXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.ValidatePassCode_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).ValidatePassCode(inValue);
            employeeByIDXMLPort = retVal.employeeByIDXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.ValidatePassCode_Result> ValidatePassCodeAsync(NMSService.NMSSernice.ValidatePassCode request) {
            return base.Channel.ValidatePassCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.GetEmployeeProjects_Result NMSService.NMSSernice.TimeSheetBotService_Port.GetEmployeeProjects(NMSService.NMSSernice.GetEmployeeProjects request) {
            return base.Channel.GetEmployeeProjects(request);
        }
        
        public int GetEmployeeProjects(string employeeNoP, ref NMSService.NMSSernice.root4 employeeProjectsXMLPort, ref string errorText) {
            NMSService.NMSSernice.GetEmployeeProjects inValue = new NMSService.NMSSernice.GetEmployeeProjects();
            inValue.employeeNoP = employeeNoP;
            inValue.employeeProjectsXMLPort = employeeProjectsXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.GetEmployeeProjects_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).GetEmployeeProjects(inValue);
            employeeProjectsXMLPort = retVal.employeeProjectsXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeProjects_Result> GetEmployeeProjectsAsync(NMSService.NMSSernice.GetEmployeeProjects request) {
            return base.Channel.GetEmployeeProjectsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.GetEmployeeTasks_Result NMSService.NMSSernice.TimeSheetBotService_Port.GetEmployeeTasks(NMSService.NMSSernice.GetEmployeeTasks request) {
            return base.Channel.GetEmployeeTasks(request);
        }
        
        public int GetEmployeeTasks(string employeeNoP, string projectNoP, ref NMSService.NMSSernice.root5 employeeTasksXMLPort, ref string errorText) {
            NMSService.NMSSernice.GetEmployeeTasks inValue = new NMSService.NMSSernice.GetEmployeeTasks();
            inValue.employeeNoP = employeeNoP;
            inValue.projectNoP = projectNoP;
            inValue.employeeTasksXMLPort = employeeTasksXMLPort;
            inValue.errorText = errorText;
            NMSService.NMSSernice.GetEmployeeTasks_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).GetEmployeeTasks(inValue);
            employeeTasksXMLPort = retVal.employeeTasksXMLPort;
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.GetEmployeeTasks_Result> GetEmployeeTasksAsync(NMSService.NMSSernice.GetEmployeeTasks request) {
            return base.Channel.GetEmployeeTasksAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NMSService.NMSSernice.AddTimeSheet_Result NMSService.NMSSernice.TimeSheetBotService_Port.AddTimeSheet(NMSService.NMSSernice.AddTimeSheet request) {
            return base.Channel.AddTimeSheet(request);
        }
        
        public int AddTimeSheet(string employeeNoP, System.DateTime dateP, string projectNoP, string assignmentCodeP, decimal qtyP, string commentP, ref string errorText) {
            NMSService.NMSSernice.AddTimeSheet inValue = new NMSService.NMSSernice.AddTimeSheet();
            inValue.employeeNoP = employeeNoP;
            inValue.dateP = dateP;
            inValue.projectNoP = projectNoP;
            inValue.assignmentCodeP = assignmentCodeP;
            inValue.qtyP = qtyP;
            inValue.commentP = commentP;
            inValue.errorText = errorText;
            NMSService.NMSSernice.AddTimeSheet_Result retVal = ((NMSService.NMSSernice.TimeSheetBotService_Port)(this)).AddTimeSheet(inValue);
            errorText = retVal.errorText;
            return retVal.return_value;
        }
        
        public System.Threading.Tasks.Task<NMSService.NMSSernice.AddTimeSheet_Result> AddTimeSheetAsync(NMSService.NMSSernice.AddTimeSheet request) {
            return base.Channel.AddTimeSheetAsync(request);
        }
    }
}
